version: '3'
services:
  radiant:
    image: "vnijs/radiant"
    ports:
      - 8787:8787
      - 9080:80
    volumes:
      - ~/Desktop:/home/rstudio/Desktop
      - ~/Dropbox:/home/rstudio/Dropbox:ro
  tensorflow:
    image: jupyter/tensorflow-notebook
    ports:
      - 8888:8888
    volumes:
      - ~/Dropbox:/work/Dropbox:ro
